apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/A-Lee/K8-manifests.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true