apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  backend_url: {{ .Values.configMap.backendUrl }}
  username: {{ .Values.configMap.username }}
  SPRING_DATASOURCE_URL: {{ .Values.configMap.sql_url }}
  fakeVal: {{ .Values.configMap.fakeVal }}
