apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  namespace: {{ .Values.namespace }}
spec:
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce